// Rebuild the framework-free browser engine from the pinned preview package.
const fs = require('node:fs');
const esbuild = require('esbuild');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const source = path.join(root, 'demo/orb-inspection/node_modules/thinking-orbs');
const result = esbuild.buildSync({
  entryPoints: [path.join(source, 'dist/engine.es.js')],
  bundle: true, write: false, format: 'iife', globalName: 'AndromityOrbEngine', minify: true,
});
const license = fs.readFileSync(path.join(source, 'LICENSE'), 'utf8');
fs.writeFileSync(path.join(root, 'src/providers/chatview/orbEngine.ts'),
  '// thinking-orbs 0.3.2, MIT. Generated by scripts/vendor-orb.cjs.\n' +
  'export const orbEngineScript = ' + JSON.stringify('/*\n' + license + '\n*/\n' + result.outputFiles[0].text) + ';\n');
