"""PR Reviewer Engine.

Analyzes unified diffs, detects bugs and security risks, and formats professional,
collapsible markdown reviews with native GitHub suggestion blocks.
"""

from __future__ import annotations

import os
import sys
from typing import Optional

DEFAULT_MODEL = "openrouter/deepseek/deepseek-v4.1-flash"
REVIEW_FOOTER = """---
<sub>Review generated by [Andromity](https://andromity.agenticmarket.dev) • [Documentation](https://andromity.agenticmarket.dev/docs)</sub>"""

SYSTEM_REVIEW_PROMPT = """You are Andromity, a senior code reviewer and security auditor.
Analyze the provided Pull Request git diff.

Format your review with extreme engineering discipline:
1. Start with an 'Overview & Key Findings' section (3 to 6 bullet points total).
2. Focus on:
   - Logic bugs, race conditions, edge cases, null dereferences
   - Security vulnerabilities (SQLi, command injection, unvalidated inputs)
   - Performance regressions
   - Missing test coverage
3. If proposing a code correction, use GitHub's native suggestion markdown format:
   ```suggestion
   <corrected line(s)>
   ```
4. Wrap detailed file-by-file feedback in collapsible HTML details tags:
   <details>
   <summary><strong>File: path/to/file.ext (Click to expand)</strong></summary>

   - Detailed observations...
   </details>
5. Keep tone objective, precise, and professional. Do NOT include generic filler or conversational greetings."""


def generate_pr_review(
    diff_text: str,
    pr_title: str,
    pr_body: str,
    model: str = DEFAULT_MODEL,
    api_key: Optional[str] = None,
    custom_prompt: Optional[str] = None,
) -> str:
    """Generate structured markdown review for a git diff using LiteLLM."""
    if not diff_text.strip():
        return f"""### Overview & Key Findings
- **Status:** No changes detected in PR diff.

{REVIEW_FOOTER}"""

    # Truncate diff if extremely large to prevent context window overflow (>80K chars)
    max_chars = 80_000
    truncated = False
    if len(diff_text) > max_chars:
        diff_text = diff_text[:max_chars]
        truncated = True

    user_content = f"""Pull Request Title: {pr_title}
Pull Request Description:
{pr_body or 'No description provided.'}

Unified Git Diff:
```diff
{diff_text}
```"""
    if truncated:
        user_content += "\n\n*(Note: Diff truncated to 80,000 characters for token efficiency)*"

    if custom_prompt:
        user_content += f"\n\nMaintainer Instructions:\n{custom_prompt}"

    # Setup API key in environment for LiteLLM if provided
    if api_key:
        if "openrouter" in model.lower() or not os.environ.get("OPENROUTER_API_KEY"):
            os.environ["OPENROUTER_API_KEY"] = api_key
        if not os.environ.get("GEMINI_API_KEY"):
            os.environ["GEMINI_API_KEY"] = api_key

    try:
        import litellm

        # Enable silent mode for clean CI logs
        litellm.suppress_debug_info = True

        completion_kwargs = {
            "model": model,
            "messages": [
                {"role": "system", "content": SYSTEM_REVIEW_PROMPT},
                {"role": "user", "content": user_content},
            ],
            "temperature": 0.2,
        }
        resolved_key = api_key or os.environ.get("OPENROUTER_API_KEY") or os.environ.get("GEMINI_API_KEY")
        if resolved_key:
            completion_kwargs["api_key"] = resolved_key

        response = litellm.completion(**completion_kwargs)

        review_content = response.choices[0].message.content or ""
        return f"{review_content.strip()}\n\n{REVIEW_FOOTER}"

    except Exception as e:
        print(f"[Andromity CI] Model execution error: {e}", file=sys.stderr)
        return f"""### Andromity Review Summary
- ⚠️ **Notice:** Review could not be generated due to an inference error: `{str(e)[:150]}`.
- Please verify your API key and model identifier (`{model}`).

{REVIEW_FOOTER}"""
